[project]
name = "bitcoint-clarity"
authors = ["LNow"]
telemetry = false
requirements = []

[repl]
costs_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
# If true, inputs are trusted after tx_sender has been checked.
trusted_sender = false
# If true, inputs are trusted after contract-caller has been checked.
trusted_caller = false
# If true, untrusted data may be passed into a private function without a
# warning, if it gets checked inside. This check will also propagate up to the
# caller.
callee_filter = false

[contracts.btc]
path = "contracts/btc.clar"
depends_on = []
