name: CI Clarinet

# Controls when the action will run.
on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main
      - dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Check contract syntax"
        uses: docker://hirosystems/clarinet:latest
        with:
          args: check
      - name: "Execute test suite"
        uses: docker://hirosystems/clarinet:latest
        with:
          args: test --coverage
      - name: "Upload code coverage"
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.lcov
